sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 2.6
  - 2.7
  - pypy3
  - 3.3
  - 3.4
  - 3.5
before_install:
  - pip install https://github.com/pyexcel/pyexcel-io/archive/master.zip
  - pip install https://github.com/pyexcel/pyexcel-xls/archive/master.zip
  - pip install https://github.com/pyexcel/pyexcel/archive/master.zip
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov